### PR TITLE
Remove deprecated cmdline options and change defaults

### PR DESCRIPTION
**Pull request by deadeyegoodwin**
Remove
--grpc-infer-thread-count
--grpc-stream-infer-thread-count
--allow-poll-model-repository
--allow-model-control

--model-control-mode default is "none"

### CODE REVIEW

**Comment by CoderHam** [comment]
Since we no longer support multiple ports should we also remove OPTION_HTTP_HEALTH_PORT and the related code?

**Comment by deadeyegoodwin** [comment]
> Since we no longer support multiple ports should we also remove OPTION_HTTP_HEALTH_PORT and the related code?

Yes, that is a good point, I will add it to this PR.

**Comment by CoderHam** [comment]
I think it would be more appropriate to rename to the `L0_multiple_ports` test to `L0_ports` or something like that

**Comment by deadeyegoodwin** [comment]
> I think it would be more appropriate to rename to the `L0_multiple_ports` test to `L0_ports` or something like that

Well, there are still multiple ports being tested, they are just not all http ports...

**Pull request merged**
