### PR TITLE
add C# example for #1272

### PR DESCRIPTION
**Pull request by turowicz**
Followed Go example functionality.

### CODE REVIEW

**Comment by turowicz** [comment]
@deadeyegoodwin please review this PR

**Comment by deadeyegoodwin** [comment]
@turowicz I've approved the PR but before I can merge you need to follow the CLA steps in https://github.com/NVIDIA/triton-inference-server/blob/master/CONTRIBUTING.md

**Comment by turowicz** [comment]
@deadeyegoodwin thanks for approving. Is there a reason for not merging it yet?

**Comment by turowicz** [comment]
@deadeyegoodwin is there a non-corporate version of CLA? I'm not contributing on behalf of any company.

**Comment by deadeyegoodwin** [comment]
> @deadeyegoodwin is there a non-corporate version of CLA? I'm not contributing on behalf of any company.

You can use the corporate CLA, just put "self" as the corporation and only list yourself in the approved submitter. Be sure to include your gitlab username in the approved submitter section.

**Comment by turowicz** [comment]
@deadeyegoodwin done

**Comment by deadeyegoodwin** [comment]
We received your CLA, that you for the contribution.

**Comment by deadeyegoodwin** [comment]
@turowicz we are in the process of moving Triton to version 2 and your c# example needs updating. Can you take a look at it on the master branch and make sure it is still working. At the least I think you need to make an adjustment because grpc_service_v2.proto is renamed to grpc_server.proto.

**Comment by turowicz** [comment]
@deadeyegoodwin can I get access to the `20.05` docker image from your private repo? I need it in order to test my code against the new version.

**Comment by deadeyegoodwin** [comment]
There is no external access to our private repo. Can you try using the master branch to test?

**Comment by turowicz** [comment]
@deadeyegoodwin how about I add the example post-release? Unfortunately I haven't got time to do a full container build on my own.

**Comment by deadeyegoodwin** [comment]
That's fine. You can submit a PR to master when you are ready and it will get included in the next release.

**Comment by turowicz** [comment]
@deadeyegoodwin congratulations on the new release. Should I now be able to use the latest image in the repository to build a new c# client example?

**Comment by deadeyegoodwin** [comment]
Yes, you will need to use the --api-version=2 flag when launching the server. And in 20.03.1 the proto file is grpc_service_v2.proto while in master it is grpc_service.proto, so after testing you will need to adjust that in your PR.

**Comment by turowicz** [comment]
@deadeyegoodwin  The V2 client work is finally underway.

**Pull request merged**
