### PR TITLE
Fix L0_storage_S3 test

### PR DESCRIPTION
**Pull request by CoderHam**

### CODE REVIEW

**Comment by GuanLuo** [comment]
Why moving the test to elsewhere, I don't think it uses models that is not public accessible.

**Comment by CoderHam** [comment]
> Why moving the test to elsewhere, I don't think it uses models that is not public accessible.

Cannot expose S3 credentials here.

**Comment by GuanLuo** [comment]
The secrets can be set as CI environment variables, right?

**Comment by CoderHam** [comment]
> Does this test both ways of using S3?
> Also you need to update the title since it still refers to gitlab.

The second way of testing by passing S3 ENV vars will be added with the follow up ticket and support for ENV vars

**Pull request merged**
